apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game
spec:
  replicas: 2            # how many Pods
  selector:
    matchLabels:
      app: snake-game    # Deployment will look for Pods with this label, says “I will manage Pods that have this label.”

  template:              # <---- THIS defines the Pod blueprint
    metadata:
      labels:
        app: snake-game  # label the Pod with this label, so Deployment can find it
    spec:                # Pod spec = what’s inside the Pod
      containers:
      - name: snake-game
        image: richuxd/snake-game:latest
        ports:
        - containerPort: 80
